image: alpine/edge
packages:
  - go
  - enet-dev
  - rsync
sources:
  - https://github.com/sauerbraten/waiter.git
environment:
  DEPLOY: p1x.pw
  GOPATH: $HOME
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81
tasks:
  - prepare_gopath: |
      mkdir -p src/github.com/sauerbraten
      mv waiter src/github.com/sauerbraten/
  - version: |
      cd src/github.com/sauerbraten/waiter
      sed -i "s/<filled in by CI service>/$(git rev-parse --short HEAD)/" config.json
  - build: |
      cd src/github.com/sauerbraten/waiter/cmd/waiter
      go get
      go build
  - deploy: |
      cd src/github.com/sauerbraten/waiter
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq bans.json config.json users.json maps.json ci@$DEPLOY:~/waiter/
      cd cmd/waiter
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq waiter ci@$DEPLOY:~/waiter/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall waiter || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd waiter; nohup ./waiter >> log.txt 2>&1 &'
