image: alpine/edge
packages:
  - autoconf
  - automake
  - g++
  - go
  - libtool
  - rsync
sources:
  - https://github.com/sauerbraten/waiter.git
  - https://github.com/lsalzman/enet.git
environment:
  DEPLOY: p1x.pw
  GOPATH: $HOME
  CGO_CFLAGS: -I $HOME/enet/include
  CGO_LDFLAGS: -L$HOME/enet/.libs/
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81 # ssh key
  - 055bbc32-4b46-4556-83c9-2927c0846daa # stats.p1x.pw admin key: ~/.statsauth_admin_key
tasks:
  - version: |
      cd waiter
      sed -i "s/<filled in by CI service>/$(git rev-parse --short HEAD)/" config.json
  - build_enet: |
      cd enet
      autoreconf -vfi
      ./configure && make
  - build: |
      cd waiter
      make all
  - deploy: |
      cd waiter
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'mkdir -p ~/waiter'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq waiter bans.json config.json users.json ~/.statsauth_admin_key ci@$DEPLOY:~/waiter/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall waiter || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd waiter; export STATSAUTH_ADMIN_NAME=p1x.pw STATSAUTH_ADMIN_KEY=$(cat .statsauth_admin_key); nohup ./waiter >> log.txt 2>&1 &'
